spring: 
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zhaoling?useSSL=false
    username: root
    password: 123
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/templates/


    
mybatis:
  type-aliases-package: com.cssl.pojo
  configuration:
    auto-mapping-behavior: FULL
    use-generated-keys: true
    
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

  #mvc:
    #static-path-pattern: /**
  #resources:
    #static-locations: classpath:/templates/,classpath:/META-NF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/